name: Build, Deploy to GitHub Pages and Deploy PR Preview

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize, closed ]

permissions:
  contents: write
  pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
  build-deploy-and-preview:
    name: Build & Preview Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Build, Deploy & PR Preview
        uses: chvmvd/build-deploy-and-preview-action@v1.2.0
        with:
          type: docusaurus
